if __name__ == '__main__':
  for i in range(10):
    print("Hello world")
    print("amenboakainaaiueo")
    print("typingtest")
    print("amennboakainaaiueo")
    print("kakinokikurinokikakikukeko")
    print("ogawadekoebimooyoideru")
    print("aiueo")
    print("kakikukeko")
    print("sashisuseso")
    print("tatitutto")
    print("naninuneno")
    print("hahihuheho")
    print("mamimumemo")
    print("yayuyo")
    print("rarirurero")
    print("wawon")